### PR TITLE
minor changes to index.php

### PR DESCRIPTION
**Pull request by torvista**

### CODE REVIEW

**Review by Dlair — APPROVED** [review]
Nice work!

**Comment by iskndrcnr** [comment]
here is my body section of index.php for choosing projects easyly
`    <body>
        <div class="container">
            <div class="content">
                <div class="title" title="Laragon">Laragon</div>
                <div class="info"><br />
                      <?php print($_SERVER['SERVER_SOFTWARE']); ?><br />
                      PHP version: <?php print phpversion(); ?>
                      <span>
                        <a title="phpinfo()" href="/?q=info">info</a>
                    </span>
                    <br />
                      Document Root: <?php print ($_SERVER['DOCUMENT_ROOT']); ?><br />
                </div>
                <div class="opt">
                    <div><a title="Getting Started" href="https://laragon.org/docs">Getting Started</a></div>
                    <?php
                    $dir = dir(".");
                    echo "<ul>";
                    while (false !== ($entry = $dir->read())) {
                       echo "<li><a href='{$entry}'>{$entry}</a></li>";
                    }
                    echo "</ul>";
                    $dir->close();
                    ?>
                </div>
            </div>
        </div>
    </body>`

**Comment by torvista** [comment]
Is this project still alive?

**Comment by leokhoa** [comment]
@torvista: Yes, it is still alive

**Comment by torvista** [comment]
Glad to hear it, I recommend it to all who ask....meanwhile can this PR be dealt with?, one way or another.

**Comment by leokhoa** [comment]
Thanks @torvista 
It looks good to me.

**Comment by torvista** [comment]
Thanks, I don't like things unresolved!!

**Pull request merged**
