### PR TITLE
updated php version

### PR DESCRIPTION
**Pull request by Lizwis**

### CODE REVIEW

**Review by simphiwehlabisa — APPROVED** [review]

**Review by AngelKrak — APPROVED** [review]

**Comment by humbertoplus** [comment]
When Planing to update completely LARAGON?????

**Comment by torvista** [comment]
The continuing inclusion of the obsolete 5.4.9 results in a bug with nginx:
https://forum.laragon.org/topic/1865/no-input-file-specified-php-pages-issue/5

**Comment by alxndr-w** [comment]
close?

**Comment by alxndr-w** [comment]
I think this PR can be closed @Lizwis as PHP 8.3 is the current version an PHP 8.4 already in the making.

**Pull request closed without merging**
